# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/rfsoc_data_pipeline_system_ila_2_0.xci
# IP: The module: 'rfsoc_data_pipeline_system_ila_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/bd_5a51.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a51 || ORIG_REF_NAME==bd_5a51} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/bd_5a51_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a51_ila_lib_0 || ORIG_REF_NAME==bd_5a51_ila_lib_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a51_ila_lib_0 || ORIG_REF_NAME==bd_5a51_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a51_ila_lib_0 || ORIG_REF_NAME==bd_5a51_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/bd_5a51_ila_lib_0_ooc.xdc

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/bd_5a51_ooc.xdc

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/rfsoc_data_pipeline_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfsoc_data_pipeline_system_ila_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/rfsoc_data_pipeline_system_ila_2_0.xci
# IP: The module: 'rfsoc_data_pipeline_system_ila_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/bd_5a51.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a51 || ORIG_REF_NAME==bd_5a51} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/bd_5a51_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a51_ila_lib_0 || ORIG_REF_NAME==bd_5a51_ila_lib_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a51_ila_lib_0 || ORIG_REF_NAME==bd_5a51_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a51_ila_lib_0 || ORIG_REF_NAME==bd_5a51_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/ip/ip_0/bd_5a51_ila_lib_0_ooc.xdc

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/bd_0/bd_5a51_ooc.xdc

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/rfsoc_data_pipeline/ip/rfsoc_data_pipeline_system_ila_2_0/rfsoc_data_pipeline_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rfsoc_data_pipeline_system_ila_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
