# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/top_level_rfsoc_data_pipeline_13_0.xci
# IP: The module: 'top_level_rfsoc_data_pipeline_13_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_0/rfsoc_data_pipeline_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_0/rfsoc_data_pipeline_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_0/rfsoc_data_pipeline_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_2_0/rfsoc_data_pipeline_axis_data_fifo_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_2_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_2_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_1/rfsoc_data_pipeline_axis_data_fifo_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_1/rfsoc_data_pipeline_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_1/rfsoc_data_pipeline_axis_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_0/rfsoc_data_pipeline_axis_data_fifo_waveform_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_2/rfsoc_data_pipeline_axis_data_fifo_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_2/rfsoc_data_pipeline_axis_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_2/rfsoc_data_pipeline_axis_dwidth_converter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_1/rfsoc_data_pipeline_axis_data_fifo_waveform_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_3/rfsoc_data_pipeline_axis_data_fifo_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_3/rfsoc_data_pipeline_axis_data_fifo_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_3/rfsoc_data_pipeline_axis_dwidth_converter_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_2/rfsoc_data_pipeline_axis_data_fifo_waveform_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_4/rfsoc_data_pipeline_axis_data_fifo_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_4/rfsoc_data_pipeline_axis_data_fifo_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_4/rfsoc_data_pipeline_axis_dwidth_converter_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_3/rfsoc_data_pipeline_axis_data_fifo_waveform_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_5/rfsoc_data_pipeline_axis_data_fifo_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_6/rfsoc_data_pipeline_axis_data_fifo_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_5/rfsoc_data_pipeline_axis_data_fifo_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_5/rfsoc_data_pipeline_axis_dwidth_converter_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_4/rfsoc_data_pipeline_axis_data_fifo_waveform_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_0/rfsoc_data_pipeline_axis_data_fifo_gpio_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_7/rfsoc_data_pipeline_axis_data_fifo_1_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_6/rfsoc_data_pipeline_axis_data_fifo_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_6/rfsoc_data_pipeline_axis_dwidth_converter_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_5/rfsoc_data_pipeline_axis_data_fifo_waveform_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_1/rfsoc_data_pipeline_axis_data_fifo_gpio_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_8/rfsoc_data_pipeline_axis_data_fifo_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_7/rfsoc_data_pipeline_axis_data_fifo_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_7/rfsoc_data_pipeline_axis_dwidth_converter_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_6/rfsoc_data_pipeline_axis_data_fifo_waveform_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_2/rfsoc_data_pipeline_axis_data_fifo_gpio_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_8/rfsoc_data_pipeline_axis_data_fifo_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_8/rfsoc_data_pipeline_axis_dwidth_converter_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_7/rfsoc_data_pipeline_axis_data_fifo_waveform_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_3/rfsoc_data_pipeline_axis_data_fifo_gpio_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_9/rfsoc_data_pipeline_axis_data_fifo_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_9/rfsoc_data_pipeline_axis_dwidth_converter_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_8/rfsoc_data_pipeline_axis_data_fifo_waveform_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_4/rfsoc_data_pipeline_axis_data_fifo_gpio_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_10/rfsoc_data_pipeline_axis_data_fifo_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_10/rfsoc_data_pipeline_axis_dwidth_converter_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_9/rfsoc_data_pipeline_axis_data_fifo_waveform_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_5/rfsoc_data_pipeline_axis_data_fifo_gpio_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_data_pipeline_13_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/top_level_rfsoc_data_pipeline_13_0.xci
# IP: The module: 'top_level_rfsoc_data_pipeline_13_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_0/rfsoc_data_pipeline_axis_data_fifo_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_0/rfsoc_data_pipeline_axis_dwidth_converter_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_0/rfsoc_data_pipeline_axis_data_fifo_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_2_0/rfsoc_data_pipeline_axis_data_fifo_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_2_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_2_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_1/rfsoc_data_pipeline_axis_data_fifo_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_1/rfsoc_data_pipeline_axis_data_fifo_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_1/rfsoc_data_pipeline_axis_dwidth_converter_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_0/rfsoc_data_pipeline_axis_data_fifo_waveform_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_2/rfsoc_data_pipeline_axis_data_fifo_1_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_2/rfsoc_data_pipeline_axis_data_fifo_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_2/rfsoc_data_pipeline_axis_dwidth_converter_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_1/rfsoc_data_pipeline_axis_data_fifo_waveform_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_3/rfsoc_data_pipeline_axis_data_fifo_1_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_3/rfsoc_data_pipeline_axis_data_fifo_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_3/rfsoc_data_pipeline_axis_dwidth_converter_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_2/rfsoc_data_pipeline_axis_data_fifo_waveform_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_4/rfsoc_data_pipeline_axis_data_fifo_1_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_4/rfsoc_data_pipeline_axis_data_fifo_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_4/rfsoc_data_pipeline_axis_dwidth_converter_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_3/rfsoc_data_pipeline_axis_data_fifo_waveform_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_5/rfsoc_data_pipeline_axis_data_fifo_1_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_6/rfsoc_data_pipeline_axis_data_fifo_1_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_5/rfsoc_data_pipeline_axis_data_fifo_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_5/rfsoc_data_pipeline_axis_dwidth_converter_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_4/rfsoc_data_pipeline_axis_data_fifo_waveform_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_0/rfsoc_data_pipeline_axis_data_fifo_gpio_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_0 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_7/rfsoc_data_pipeline_axis_data_fifo_1_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_6/rfsoc_data_pipeline_axis_data_fifo_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_6/rfsoc_data_pipeline_axis_dwidth_converter_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_5/rfsoc_data_pipeline_axis_data_fifo_waveform_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_1/rfsoc_data_pipeline_axis_data_fifo_gpio_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_1 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_1_8/rfsoc_data_pipeline_axis_data_fifo_1_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_1_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_7/rfsoc_data_pipeline_axis_data_fifo_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_7/rfsoc_data_pipeline_axis_dwidth_converter_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_6/rfsoc_data_pipeline_axis_data_fifo_waveform_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_2/rfsoc_data_pipeline_axis_data_fifo_gpio_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_2 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_8/rfsoc_data_pipeline_axis_data_fifo_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_8/rfsoc_data_pipeline_axis_dwidth_converter_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_7/rfsoc_data_pipeline_axis_data_fifo_waveform_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_7 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_3/rfsoc_data_pipeline_axis_data_fifo_gpio_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_3 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_9/rfsoc_data_pipeline_axis_data_fifo_0_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_9/rfsoc_data_pipeline_axis_dwidth_converter_0_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_8/rfsoc_data_pipeline_axis_data_fifo_waveform_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_8 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_4/rfsoc_data_pipeline_axis_data_fifo_gpio_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_4 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_0_10/rfsoc_data_pipeline_axis_data_fifo_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_dwidth_converter_0_10/rfsoc_data_pipeline_axis_dwidth_converter_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_waveform_9/rfsoc_data_pipeline_axis_data_fifo_waveform_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_axis_data_fifo_gpio_5/rfsoc_data_pipeline_axis_data_fifo_gpio_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_13_0_1/src/rfsoc_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_data_pipeline_13_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
