# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/top_level_rf_data_pipeline_1_1.xci
# IP: The module: 'top_level_rf_data_pipeline_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_0c61_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_0c61_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_cc30_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_cc30_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_ccc0_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_ccc0_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/top_level_rf_data_pipeline_1_1.xci
# IP: The module: 'top_level_rf_data_pipeline_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_0c61_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_0c61_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_cc30_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_cc30_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_ccc0_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/bd_ccc0_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_1_1/src/rf_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
