set_property SRC_FILE_INFO {cfile:C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/constrs_1/new/elab_design.xdc rfile:../../../microblaze_stream_test.srcs/constrs_1/new/elab_design.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP22 [get_ports diff_clock_rtl_clk_p]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV25 [get_ports reset_in]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB22 [get_ports uart_rx]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB23 [get_ports uart_tx]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A3 [get_ports dac0_clk_clk_n]
