# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/elab_design.xdc

# Block Designs: bd/microblaze_test_top/microblaze_test_top.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_test_top || ORIG_REF_NAME==microblaze_test_top} -quiet] -quiet

# IP: bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/microblaze_test_top_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_test_top_microblaze_mcs_0_0 || ORIG_REF_NAME==microblaze_test_top_microblaze_mcs_0_0} -quiet] -quiet

# IP: bd/microblaze_test_top/ip/microblaze_test_top_clk_wiz_0/microblaze_test_top_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_test_top_clk_wiz_0 || ORIG_REF_NAME==microblaze_test_top_clk_wiz_0} -quiet] -quiet

# IP: bd/microblaze_test_top/ip/microblaze_test_top_util_vector_logic_0_0/microblaze_test_top_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==microblaze_test_top_util_vector_logic_0_0 || ORIG_REF_NAME==microblaze_test_top_util_vector_logic_0_0} -quiet] -quiet

# XDC: bd/microblaze_test_top/microblaze_test_top_ooc.xdc
