# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 3
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache {C:/Users/Marandi Group B241/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-8868-DESKTOP-6ILET8A/incrSyn}
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xczu29dr-ffvf1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.cache/wt [current_project]
set_property parent.project_path C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu1275:part0:1.0 [current_project]
set_property ip_output_repo c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/hdl/microblaze_test_top_wrapper.v
add_files C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/microblaze_test_top.bd
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_4f04_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_4f04_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_4f04_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_4f04_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_4f04_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_4f04_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_4f04_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_4f04_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_4f04_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_4f04_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/bd_4f04_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/microblaze_test_top_microblaze_mcs_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/microblaze_test_top_microblaze_mcs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_clk_wiz_0/microblaze_test_top_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_clk_wiz_0/microblaze_test_top_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_clk_wiz_0/microblaze_test_top_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/microblaze_test_top_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/microblaze_test_top/ip/microblaze_test_top_microblaze_mcs_0_0/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/constrs_1/new/elab_design.xdc
set_property used_in_implementation false [get_files C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/constrs_1/new/elab_design.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top microblaze_test_top_wrapper -part xczu29dr-ffvf1760-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef microblaze_test_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file microblaze_test_top_wrapper_utilization_synth.rpt -pb microblaze_test_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
