# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_trigger_controller_0_0/top_level_trigger_controller_0_0.xci
# IP: The module: 'top_level_trigger_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_trigger_controller_0_0/src/trigger_controller_axis_data_fifo_0_0/trigger_controller_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trigger_controller_axis_data_fifo_0_0 || ORIG_REF_NAME==trigger_controller_axis_data_fifo_0_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_trigger_controller_0_0/src/trigger_controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_trigger_controller_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_trigger_controller_0_0/top_level_trigger_controller_0_0.xci
# IP: The module: 'top_level_trigger_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_trigger_controller_0_0/src/trigger_controller_axis_data_fifo_0_0/trigger_controller_axis_data_fifo_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==trigger_controller_axis_data_fifo_0_0 || ORIG_REF_NAME==trigger_controller_axis_data_fifo_0_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_trigger_controller_0_0/src/trigger_controller_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_trigger_controller_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
