# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/el_des.xdc

# Block Designs: bd/top_level/top_level.bd
# Block Designs: The module: 'top_level' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/top_level/ip/top_level_microblaze_mcs_0_2/top_level_microblaze_mcs_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_mcs_0_2 || ORIG_REF_NAME==top_level_microblaze_mcs_0_2} -quiet] -quiet

# IP: bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_2 || ORIG_REF_NAME==top_level_clk_wiz_2} -quiet] -quiet

# IP: bd/top_level/ip/top_level_util_vector_logic_0_3/top_level_util_vector_logic_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_util_vector_logic_0_3 || ORIG_REF_NAME==top_level_util_vector_logic_0_3} -quiet] -quiet

# XDC: bd/top_level/top_level_ooc.xdc
