# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/elab_design.xdc

# Block Designs: bd/top_level/top_level.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_microblaze_0_0/top_level_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_0_0 || ORIG_REF_NAME==top_level_microblaze_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_dlmb_v10_0/top_level_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_dlmb_v10_0 || ORIG_REF_NAME==top_level_dlmb_v10_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ilmb_v10_0/top_level_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ilmb_v10_0 || ORIG_REF_NAME==top_level_ilmb_v10_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_dlmb_bram_if_cntlr_0/top_level_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_level_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ilmb_bram_if_cntlr_0/top_level_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==top_level_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_lmb_bram_0/top_level_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_lmb_bram_0 || ORIG_REF_NAME==top_level_lmb_bram_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xbar_0/top_level_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_xbar_0 || ORIG_REF_NAME==top_level_xbar_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_microblaze_0_axi_periph_0/top_level_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_0_axi_periph_0 || ORIG_REF_NAME==top_level_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_mdm_1_0/top_level_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_mdm_1_0 || ORIG_REF_NAME==top_level_mdm_1_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_clk_wiz_1_0/top_level_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_1_0 || ORIG_REF_NAME==top_level_clk_wiz_1_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_clk_wiz_1_100M_0/top_level_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==top_level_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_util_vector_logic_0_0/top_level_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_util_vector_logic_0_0 || ORIG_REF_NAME==top_level_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_uartlite_0_0/top_level_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axi_uartlite_0_0 || ORIG_REF_NAME==top_level_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_gpio_0_0/top_level_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axi_gpio_0_0 || ORIG_REF_NAME==top_level_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_usp_rf_data_converter_0_0/top_level_usp_rf_data_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/top_level_rfsoc_data_pipeline_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rfsoc_data_pipeline_0_0 || ORIG_REF_NAME==top_level_rfsoc_data_pipeline_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rfsoc_data_pipeline_1_0/top_level_rfsoc_data_pipeline_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rfsoc_data_pipeline_1_0 || ORIG_REF_NAME==top_level_rfsoc_data_pipeline_1_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_proc_sys_reset_0_0/top_level_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_proc_sys_reset_0_0 || ORIG_REF_NAME==top_level_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_count_buffer_0_0/top_level_count_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_count_buffer_0_0 || ORIG_REF_NAME==top_level_count_buffer_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_0_0/top_level_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_0_0 || ORIG_REF_NAME==top_level_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_gpio_trigger_breakin_0_0/top_level_gpio_trigger_breakin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_gpio_trigger_breakin_0_0 || ORIG_REF_NAME==top_level_gpio_trigger_breakin_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_trigger_buffer_0_0/top_level_trigger_buffer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_trigger_buffer_0_0 || ORIG_REF_NAME==top_level_trigger_buffer_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rfsoc_data_pipeline_2_0/top_level_rfsoc_data_pipeline_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rfsoc_data_pipeline_2_0 || ORIG_REF_NAME==top_level_rfsoc_data_pipeline_2_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rfsoc_data_pipeline_3_0/top_level_rfsoc_data_pipeline_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rfsoc_data_pipeline_3_0 || ORIG_REF_NAME==top_level_rfsoc_data_pipeline_3_0} -quiet] -quiet

# XDC: bd/top_level/top_level_ooc.xdc
