# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4.xci
# IP: The module: 'top_level_axi_dma_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_axi_dma_0_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_axi_dma_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_axi_dma_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4.xci
# IP: The module: 'top_level_axi_dma_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_axi_dma_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_axi_dma_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/james/fpga_projects/arm_axi_test/arm_axi_test.srcs/sources_1/bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_axi_dma_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
