set_property PACKAGE_PIN A3 [get_ports dac0_clk_clk_n]
set_property PACKAGE_PIN AP22 [get_ports diff_clock_rtl_clk_p]
set_property IOSTANDARD LVDS [get_ports diff_clock_rtl_clk_p]
set_property PACKAGE_PIN AV25 [get_ports resetn]
set_property IOSTANDARD LVCMOS18 [get_ports resetn]
set_property PACKAGE_PIN BB23 [get_ports tx_0]
set_property PACKAGE_PIN BB22 [get_ports rx_0]
set_property IOSTANDARD LVCMOS18 [get_ports rx_0]
set_property IOSTANDARD LVCMOS18 [get_ports tx_0]
set_property PACKAGE_PIN AY22 [get_ports ext_trigger_0_0]
set_property IOSTANDARD LVCMOS18 [get_ports ext_trigger_0_0]

