webtalk_init -webtalk_dir C:\\james\\fpga_projects\\rfsoc_controller\\rfsoc_controller.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-07-01 18:17:53" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211753168_1777545763_0_929" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "81cg4b0cosa90t206m8vgl0354" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.377 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1562024070957" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key hwid -value "1562016393742" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key bspid -value "1562016421157" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key projSize -value "400.8203125" -context "sdk\\\\application/1562024070957"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key DebugCount -value "6" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1562030273475"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1562030273475"
webtalk_transmit -clientid 3852097382 -regid "211753168_1777545763_0_929" -xml C:\\james\\fpga_projects\\rfsoc_controller\\rfsoc_controller.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\james\\fpga_projects\\rfsoc_controller\\rfsoc_controller.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\james\\fpga_projects\\rfsoc_controller\\rfsoc_controller.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
