# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_xbar_1/top_level_xbar_1.xci
# IP: The module: 'top_level_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_xbar_1/top_level_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_xbar_1/top_level_xbar_1.xci
# IP: The module: 'top_level_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_xbar_1/top_level_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
