# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/top_level_rf_data_pipeline_0_3.xci
# IP: The module: 'top_level_rf_data_pipeline_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_0_0/rf_data_pipeline_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_0_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_dwidth_converter_0_0/rf_data_pipeline_axis_dwidth_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_0 || ORIG_REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_1_0/rf_data_pipeline_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_1_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_1_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_2_0/rf_data_pipeline_axis_data_fifo_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_2_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_2_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_3_0/rf_data_pipeline_axis_data_fifo_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_3_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_3_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_0_1/rf_data_pipeline_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_0_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_dwidth_converter_0_1/rf_data_pipeline_axis_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_1 || ORIG_REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_1_1/rf_data_pipeline_axis_data_fifo_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_1_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_1_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_2_1/rf_data_pipeline_axis_data_fifo_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_2_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_2_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_3_1/rf_data_pipeline_axis_data_fifo_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_3_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_3_1} -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_0c61_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_0c61_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_cc30_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_cc30_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_ccc0_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_ccc0_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/top_level_rf_data_pipeline_0_3.xci
# IP: The module: 'top_level_rf_data_pipeline_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_0_0/rf_data_pipeline_axis_data_fifo_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_0_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_dwidth_converter_0_0/rf_data_pipeline_axis_dwidth_converter_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_0 || ORIG_REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_1_0/rf_data_pipeline_axis_data_fifo_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_1_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_1_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_2_0/rf_data_pipeline_axis_data_fifo_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_2_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_2_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_3_0/rf_data_pipeline_axis_data_fifo_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_3_0 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_3_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_0_1/rf_data_pipeline_axis_data_fifo_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_0_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_dwidth_converter_0_1/rf_data_pipeline_axis_dwidth_converter_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_1 || ORIG_REF_NAME==rf_data_pipeline_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_1_1/rf_data_pipeline_axis_data_fifo_1_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_1_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_1_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_2_1/rf_data_pipeline_axis_data_fifo_2_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_2_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_2_1} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_axis_data_fifo_3_1/rf_data_pipeline_axis_data_fifo_3_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rf_data_pipeline_axis_data_fifo_3_1 || ORIG_REF_NAME==rf_data_pipeline_axis_data_fifo_3_1} -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_0c61_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_0c61_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_cc30_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_cc30_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_system_ila_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_ccc0_ila_lib_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/bd_ccc0_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_system_ila_2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rf_data_pipeline_0_3/src/rf_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rf_data_pipeline_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
