# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_level/top_level.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_zynq_ultra_ps_e_0_2/top_level_zynq_ultra_ps_e_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_zynq_ultra_ps_e_0_2 || ORIG_REF_NAME==top_level_zynq_ultra_ps_e_0_2} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_dma_0_4/top_level_axi_dma_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axi_dma_0_4 || ORIG_REF_NAME==top_level_axi_dma_0_4} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_smc_5/top_level_axi_smc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axi_smc_5 || ORIG_REF_NAME==top_level_axi_smc_5} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_ps8_0_100M_0/top_level_rst_ps8_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rst_ps8_0_100M_0 || ORIG_REF_NAME==top_level_rst_ps8_0_100M_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ps8_0_axi_periph_5/top_level_ps8_0_axi_periph_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ps8_0_axi_periph_5 || ORIG_REF_NAME==top_level_ps8_0_axi_periph_5} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xlconcat_0_1/top_level_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_xlconcat_0_1 || ORIG_REF_NAME==top_level_xlconcat_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_0_1/top_level_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_0_1 || ORIG_REF_NAME==top_level_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_auto_ds_5/top_level_auto_ds_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_auto_ds_5 || ORIG_REF_NAME==top_level_auto_ds_5} -quiet] -quiet

# IP: bd/top_level/ip/top_level_auto_pc_5/top_level_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_auto_pc_5 || ORIG_REF_NAME==top_level_auto_pc_5} -quiet] -quiet

# IP: bd/top_level/ip/top_level_system_ila_0_0/top_level_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_system_ila_0_0 || ORIG_REF_NAME==top_level_system_ila_0_0} -quiet] -quiet

# XDC: bd/top_level/top_level_ooc.xdc
