// Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2019.1 (win64) Build 2552052 Fri May 24 14:49:42 MDT 2019
// Date        : Mon Jul 15 10:45:34 2019
// Host        : DESKTOP-6ILET8A running 64-bit major release  (build 9200)
// Command     : write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
//               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ top_level_microblaze_0_0_stub.v
// Design      : top_level_microblaze_0_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xczu29dr-ffvf1760-2-e
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* x_core_info = "MicroBlaze,Vivado 2019.1" *)
module decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix(Clk, Reset, Interrupt, Interrupt_Address, 
  Interrupt_Ack, Instr_Addr, Instr, IFetch, I_AS, IReady, IWAIT, ICE, IUE, Data_Addr, Data_Read, 
  Data_Write, D_AS, Read_Strobe, Write_Strobe, DReady, DWait, DCE, DUE, Byte_Enable, M_AXI_DP_AWADDR, 
  M_AXI_DP_AWPROT, M_AXI_DP_AWVALID, M_AXI_DP_AWREADY, M_AXI_DP_WDATA, M_AXI_DP_WSTRB, 
  M_AXI_DP_WVALID, M_AXI_DP_WREADY, M_AXI_DP_BRESP, M_AXI_DP_BVALID, M_AXI_DP_BREADY, 
  M_AXI_DP_ARADDR, M_AXI_DP_ARPROT, M_AXI_DP_ARVALID, M_AXI_DP_ARREADY, M_AXI_DP_RDATA, 
  M_AXI_DP_RRESP, M_AXI_DP_RVALID, M_AXI_DP_RREADY, Dbg_Clk, Dbg_TDI, Dbg_TDO, Dbg_Reg_En, 
  Dbg_Shift, Dbg_Capture, Dbg_Update, Debug_Rst, Dbg_Disable, M0_AXIS_TLAST, M0_AXIS_TDATA, 
  M0_AXIS_TVALID, M0_AXIS_TREADY, M1_AXIS_TLAST, M1_AXIS_TDATA, M1_AXIS_TVALID, 
  M1_AXIS_TREADY, M2_AXIS_TLAST, M2_AXIS_TDATA, M2_AXIS_TVALID, M2_AXIS_TREADY, 
  M3_AXIS_TLAST, M3_AXIS_TDATA, M3_AXIS_TVALID, M3_AXIS_TREADY, M4_AXIS_TLAST, M4_AXIS_TDATA, 
  M4_AXIS_TVALID, M4_AXIS_TREADY, M5_AXIS_TLAST, M5_AXIS_TDATA, M5_AXIS_TVALID, 
  M5_AXIS_TREADY, M6_AXIS_TLAST, M6_AXIS_TDATA, M6_AXIS_TVALID, M6_AXIS_TREADY, 
  M7_AXIS_TLAST, M7_AXIS_TDATA, M7_AXIS_TVALID, M7_AXIS_TREADY, M8_AXIS_TLAST, M8_AXIS_TDATA, 
  M8_AXIS_TVALID, M8_AXIS_TREADY, M9_AXIS_TLAST, M9_AXIS_TDATA, M9_AXIS_TVALID, 
  M9_AXIS_TREADY, M10_AXIS_TLAST, M10_AXIS_TDATA, M10_AXIS_TVALID, M10_AXIS_TREADY, 
  M11_AXIS_TLAST, M11_AXIS_TDATA, M11_AXIS_TVALID, M11_AXIS_TREADY, M12_AXIS_TLAST, 
  M12_AXIS_TDATA, M12_AXIS_TVALID, M12_AXIS_TREADY, M13_AXIS_TLAST, M13_AXIS_TDATA, 
  M13_AXIS_TVALID, M13_AXIS_TREADY, M14_AXIS_TLAST, M14_AXIS_TDATA, M14_AXIS_TVALID, 
  M14_AXIS_TREADY, M15_AXIS_TLAST, M15_AXIS_TDATA, M15_AXIS_TVALID, M15_AXIS_TREADY, 
  S0_AXIS_TLAST, S0_AXIS_TDATA, S0_AXIS_TVALID, S0_AXIS_TREADY, S1_AXIS_TLAST, S1_AXIS_TDATA, 
  S1_AXIS_TVALID, S1_AXIS_TREADY, S2_AXIS_TLAST, S2_AXIS_TDATA, S2_AXIS_TVALID, 
  S2_AXIS_TREADY, S3_AXIS_TLAST, S3_AXIS_TDATA, S3_AXIS_TVALID, S3_AXIS_TREADY, 
  S4_AXIS_TLAST, S4_AXIS_TDATA, S4_AXIS_TVALID, S4_AXIS_TREADY, S5_AXIS_TLAST, S5_AXIS_TDATA, 
  S5_AXIS_TVALID, S5_AXIS_TREADY, S6_AXIS_TLAST, S6_AXIS_TDATA, S6_AXIS_TVALID, 
  S6_AXIS_TREADY, S7_AXIS_TLAST, S7_AXIS_TDATA, S7_AXIS_TVALID, S7_AXIS_TREADY, 
  S8_AXIS_TLAST, S8_AXIS_TDATA, S8_AXIS_TVALID, S8_AXIS_TREADY, S9_AXIS_TLAST, S9_AXIS_TDATA, 
  S9_AXIS_TVALID, S9_AXIS_TREADY, S10_AXIS_TLAST, S10_AXIS_TDATA, S10_AXIS_TVALID, 
  S10_AXIS_TREADY, S11_AXIS_TLAST, S11_AXIS_TDATA, S11_AXIS_TVALID, S11_AXIS_TREADY, 
  S12_AXIS_TLAST, S12_AXIS_TDATA, S12_AXIS_TVALID, S12_AXIS_TREADY, S13_AXIS_TLAST, 
  S13_AXIS_TDATA, S13_AXIS_TVALID, S13_AXIS_TREADY, S14_AXIS_TLAST, S14_AXIS_TDATA, 
  S14_AXIS_TVALID, S14_AXIS_TREADY, S15_AXIS_TLAST, S15_AXIS_TDATA, S15_AXIS_TVALID, 
  S15_AXIS_TREADY)
/* synthesis syn_black_box black_box_pad_pin="Clk,Reset,Interrupt,Interrupt_Address[0:31],Interrupt_Ack[0:1],Instr_Addr[0:31],Instr[0:31],IFetch,I_AS,IReady,IWAIT,ICE,IUE,Data_Addr[0:31],Data_Read[0:31],Data_Write[0:31],D_AS,Read_Strobe,Write_Strobe,DReady,DWait,DCE,DUE,Byte_Enable[0:3],M_AXI_DP_AWADDR[31:0],M_AXI_DP_AWPROT[2:0],M_AXI_DP_AWVALID,M_AXI_DP_AWREADY,M_AXI_DP_WDATA[31:0],M_AXI_DP_WSTRB[3:0],M_AXI_DP_WVALID,M_AXI_DP_WREADY,M_AXI_DP_BRESP[1:0],M_AXI_DP_BVALID,M_AXI_DP_BREADY,M_AXI_DP_ARADDR[31:0],M_AXI_DP_ARPROT[2:0],M_AXI_DP_ARVALID,M_AXI_DP_ARREADY,M_AXI_DP_RDATA[31:0],M_AXI_DP_RRESP[1:0],M_AXI_DP_RVALID,M_AXI_DP_RREADY,Dbg_Clk,Dbg_TDI,Dbg_TDO,Dbg_Reg_En[0:7],Dbg_Shift,Dbg_Capture,Dbg_Update,Debug_Rst,Dbg_Disable,M0_AXIS_TLAST,M0_AXIS_TDATA[31:0],M0_AXIS_TVALID,M0_AXIS_TREADY,M1_AXIS_TLAST,M1_AXIS_TDATA[31:0],M1_AXIS_TVALID,M1_AXIS_TREADY,M2_AXIS_TLAST,M2_AXIS_TDATA[31:0],M2_AXIS_TVALID,M2_AXIS_TREADY,M3_AXIS_TLAST,M3_AXIS_TDATA[31:0],M3_AXIS_TVALID,M3_AXIS_TREADY,M4_AXIS_TLAST,M4_AXIS_TDATA[31:0],M4_AXIS_TVALID,M4_AXIS_TREADY,M5_AXIS_TLAST,M5_AXIS_TDATA[31:0],M5_AXIS_TVALID,M5_AXIS_TREADY,M6_AXIS_TLAST,M6_AXIS_TDATA[31:0],M6_AXIS_TVALID,M6_AXIS_TREADY,M7_AXIS_TLAST,M7_AXIS_TDATA[31:0],M7_AXIS_TVALID,M7_AXIS_TREADY,M8_AXIS_TLAST,M8_AXIS_TDATA[31:0],M8_AXIS_TVALID,M8_AXIS_TREADY,M9_AXIS_TLAST,M9_AXIS_TDATA[31:0],M9_AXIS_TVALID,M9_AXIS_TREADY,M10_AXIS_TLAST,M10_AXIS_TDATA[31:0],M10_AXIS_TVALID,M10_AXIS_TREADY,M11_AXIS_TLAST,M11_AXIS_TDATA[31:0],M11_AXIS_TVALID,M11_AXIS_TREADY,M12_AXIS_TLAST,M12_AXIS_TDATA[31:0],M12_AXIS_TVALID,M12_AXIS_TREADY,M13_AXIS_TLAST,M13_AXIS_TDATA[31:0],M13_AXIS_TVALID,M13_AXIS_TREADY,M14_AXIS_TLAST,M14_AXIS_TDATA[31:0],M14_AXIS_TVALID,M14_AXIS_TREADY,M15_AXIS_TLAST,M15_AXIS_TDATA[31:0],M15_AXIS_TVALID,M15_AXIS_TREADY,S0_AXIS_TLAST,S0_AXIS_TDATA[31:0],S0_AXIS_TVALID,S0_AXIS_TREADY,S1_AXIS_TLAST,S1_AXIS_TDATA[31:0],S1_AXIS_TVALID,S1_AXIS_TREADY,S2_AXIS_TLAST,S2_AXIS_TDATA[31:0],S2_AXIS_TVALID,S2_AXIS_TREADY,S3_AXIS_TLAST,S3_AXIS_TDATA[31:0],S3_AXIS_TVALID,S3_AXIS_TREADY,S4_AXIS_TLAST,S4_AXIS_TDATA[31:0],S4_AXIS_TVALID,S4_AXIS_TREADY,S5_AXIS_TLAST,S5_AXIS_TDATA[31:0],S5_AXIS_TVALID,S5_AXIS_TREADY,S6_AXIS_TLAST,S6_AXIS_TDATA[31:0],S6_AXIS_TVALID,S6_AXIS_TREADY,S7_AXIS_TLAST,S7_AXIS_TDATA[31:0],S7_AXIS_TVALID,S7_AXIS_TREADY,S8_AXIS_TLAST,S8_AXIS_TDATA[31:0],S8_AXIS_TVALID,S8_AXIS_TREADY,S9_AXIS_TLAST,S9_AXIS_TDATA[31:0],S9_AXIS_TVALID,S9_AXIS_TREADY,S10_AXIS_TLAST,S10_AXIS_TDATA[31:0],S10_AXIS_TVALID,S10_AXIS_TREADY,S11_AXIS_TLAST,S11_AXIS_TDATA[31:0],S11_AXIS_TVALID,S11_AXIS_TREADY,S12_AXIS_TLAST,S12_AXIS_TDATA[31:0],S12_AXIS_TVALID,S12_AXIS_TREADY,S13_AXIS_TLAST,S13_AXIS_TDATA[31:0],S13_AXIS_TVALID,S13_AXIS_TREADY,S14_AXIS_TLAST,S14_AXIS_TDATA[31:0],S14_AXIS_TVALID,S14_AXIS_TREADY,S15_AXIS_TLAST,S15_AXIS_TDATA[31:0],S15_AXIS_TVALID,S15_AXIS_TREADY" */;
  input Clk;
  input Reset;
  input Interrupt;
  input [0:31]Interrupt_Address;
  output [0:1]Interrupt_Ack;
  output [0:31]Instr_Addr;
  input [0:31]Instr;
  output IFetch;
  output I_AS;
  input IReady;
  input IWAIT;
  input ICE;
  input IUE;
  output [0:31]Data_Addr;
  input [0:31]Data_Read;
  output [0:31]Data_Write;
  output D_AS;
  output Read_Strobe;
  output Write_Strobe;
  input DReady;
  input DWait;
  input DCE;
  input DUE;
  output [0:3]Byte_Enable;
  output [31:0]M_AXI_DP_AWADDR;
  output [2:0]M_AXI_DP_AWPROT;
  output M_AXI_DP_AWVALID;
  input M_AXI_DP_AWREADY;
  output [31:0]M_AXI_DP_WDATA;
  output [3:0]M_AXI_DP_WSTRB;
  output M_AXI_DP_WVALID;
  input M_AXI_DP_WREADY;
  input [1:0]M_AXI_DP_BRESP;
  input M_AXI_DP_BVALID;
  output M_AXI_DP_BREADY;
  output [31:0]M_AXI_DP_ARADDR;
  output [2:0]M_AXI_DP_ARPROT;
  output M_AXI_DP_ARVALID;
  input M_AXI_DP_ARREADY;
  input [31:0]M_AXI_DP_RDATA;
  input [1:0]M_AXI_DP_RRESP;
  input M_AXI_DP_RVALID;
  output M_AXI_DP_RREADY;
  input Dbg_Clk;
  input Dbg_TDI;
  output Dbg_TDO;
  input [0:7]Dbg_Reg_En;
  input Dbg_Shift;
  input Dbg_Capture;
  input Dbg_Update;
  input Debug_Rst;
  input Dbg_Disable;
  output M0_AXIS_TLAST;
  output [31:0]M0_AXIS_TDATA;
  output M0_AXIS_TVALID;
  input M0_AXIS_TREADY;
  output M1_AXIS_TLAST;
  output [31:0]M1_AXIS_TDATA;
  output M1_AXIS_TVALID;
  input M1_AXIS_TREADY;
  output M2_AXIS_TLAST;
  output [31:0]M2_AXIS_TDATA;
  output M2_AXIS_TVALID;
  input M2_AXIS_TREADY;
  output M3_AXIS_TLAST;
  output [31:0]M3_AXIS_TDATA;
  output M3_AXIS_TVALID;
  input M3_AXIS_TREADY;
  output M4_AXIS_TLAST;
  output [31:0]M4_AXIS_TDATA;
  output M4_AXIS_TVALID;
  input M4_AXIS_TREADY;
  output M5_AXIS_TLAST;
  output [31:0]M5_AXIS_TDATA;
  output M5_AXIS_TVALID;
  input M5_AXIS_TREADY;
  output M6_AXIS_TLAST;
  output [31:0]M6_AXIS_TDATA;
  output M6_AXIS_TVALID;
  input M6_AXIS_TREADY;
  output M7_AXIS_TLAST;
  output [31:0]M7_AXIS_TDATA;
  output M7_AXIS_TVALID;
  input M7_AXIS_TREADY;
  output M8_AXIS_TLAST;
  output [31:0]M8_AXIS_TDATA;
  output M8_AXIS_TVALID;
  input M8_AXIS_TREADY;
  output M9_AXIS_TLAST;
  output [31:0]M9_AXIS_TDATA;
  output M9_AXIS_TVALID;
  input M9_AXIS_TREADY;
  output M10_AXIS_TLAST;
  output [31:0]M10_AXIS_TDATA;
  output M10_AXIS_TVALID;
  input M10_AXIS_TREADY;
  output M11_AXIS_TLAST;
  output [31:0]M11_AXIS_TDATA;
  output M11_AXIS_TVALID;
  input M11_AXIS_TREADY;
  output M12_AXIS_TLAST;
  output [31:0]M12_AXIS_TDATA;
  output M12_AXIS_TVALID;
  input M12_AXIS_TREADY;
  output M13_AXIS_TLAST;
  output [31:0]M13_AXIS_TDATA;
  output M13_AXIS_TVALID;
  input M13_AXIS_TREADY;
  output M14_AXIS_TLAST;
  output [31:0]M14_AXIS_TDATA;
  output M14_AXIS_TVALID;
  input M14_AXIS_TREADY;
  output M15_AXIS_TLAST;
  output [31:0]M15_AXIS_TDATA;
  output M15_AXIS_TVALID;
  input M15_AXIS_TREADY;
  input S0_AXIS_TLAST;
  input [31:0]S0_AXIS_TDATA;
  input S0_AXIS_TVALID;
  output S0_AXIS_TREADY;
  input S1_AXIS_TLAST;
  input [31:0]S1_AXIS_TDATA;
  input S1_AXIS_TVALID;
  output S1_AXIS_TREADY;
  input S2_AXIS_TLAST;
  input [31:0]S2_AXIS_TDATA;
  input S2_AXIS_TVALID;
  output S2_AXIS_TREADY;
  input S3_AXIS_TLAST;
  input [31:0]S3_AXIS_TDATA;
  input S3_AXIS_TVALID;
  output S3_AXIS_TREADY;
  input S4_AXIS_TLAST;
  input [31:0]S4_AXIS_TDATA;
  input S4_AXIS_TVALID;
  output S4_AXIS_TREADY;
  input S5_AXIS_TLAST;
  input [31:0]S5_AXIS_TDATA;
  input S5_AXIS_TVALID;
  output S5_AXIS_TREADY;
  input S6_AXIS_TLAST;
  input [31:0]S6_AXIS_TDATA;
  input S6_AXIS_TVALID;
  output S6_AXIS_TREADY;
  input S7_AXIS_TLAST;
  input [31:0]S7_AXIS_TDATA;
  input S7_AXIS_TVALID;
  output S7_AXIS_TREADY;
  input S8_AXIS_TLAST;
  input [31:0]S8_AXIS_TDATA;
  input S8_AXIS_TVALID;
  output S8_AXIS_TREADY;
  input S9_AXIS_TLAST;
  input [31:0]S9_AXIS_TDATA;
  input S9_AXIS_TVALID;
  output S9_AXIS_TREADY;
  input S10_AXIS_TLAST;
  input [31:0]S10_AXIS_TDATA;
  input S10_AXIS_TVALID;
  output S10_AXIS_TREADY;
  input S11_AXIS_TLAST;
  input [31:0]S11_AXIS_TDATA;
  input S11_AXIS_TVALID;
  output S11_AXIS_TREADY;
  input S12_AXIS_TLAST;
  input [31:0]S12_AXIS_TDATA;
  input S12_AXIS_TVALID;
  output S12_AXIS_TREADY;
  input S13_AXIS_TLAST;
  input [31:0]S13_AXIS_TDATA;
  input S13_AXIS_TVALID;
  output S13_AXIS_TREADY;
  input S14_AXIS_TLAST;
  input [31:0]S14_AXIS_TDATA;
  input S14_AXIS_TVALID;
  output S14_AXIS_TREADY;
  input S15_AXIS_TLAST;
  input [31:0]S15_AXIS_TDATA;
  input S15_AXIS_TVALID;
  output S15_AXIS_TREADY;
endmodule
