# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/elab_design.xdc

# Block Designs: bd/top_level/top_level.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level || ORIG_REF_NAME==top_level} -quiet] -quiet

# IP: bd/top_level/ip/top_level_microblaze_0_1/top_level_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_0_1 || ORIG_REF_NAME==top_level_microblaze_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_dlmb_v10_1/top_level_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_dlmb_v10_1 || ORIG_REF_NAME==top_level_dlmb_v10_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ilmb_v10_1/top_level_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ilmb_v10_1 || ORIG_REF_NAME==top_level_ilmb_v10_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_dlmb_bram_if_cntlr_1/top_level_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==top_level_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_ilmb_bram_if_cntlr_1/top_level_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==top_level_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_lmb_bram_1/top_level_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_lmb_bram_1 || ORIG_REF_NAME==top_level_lmb_bram_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_xbar_1/top_level_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_xbar_1 || ORIG_REF_NAME==top_level_xbar_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_microblaze_0_axi_periph_1/top_level_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_0_axi_periph_1 || ORIG_REF_NAME==top_level_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_mdm_1_1/top_level_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_mdm_1_1 || ORIG_REF_NAME==top_level_mdm_1_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_clk_wiz_1_1/top_level_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_1_1 || ORIG_REF_NAME==top_level_clk_wiz_1_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_clk_wiz_1_100M_1/top_level_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==top_level_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_util_vector_logic_0_1/top_level_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_util_vector_logic_0_1 || ORIG_REF_NAME==top_level_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_uartlite_0_1/top_level_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axi_uartlite_0_1 || ORIG_REF_NAME==top_level_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axi_gpio_0_1/top_level_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axi_gpio_0_1 || ORIG_REF_NAME==top_level_axi_gpio_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_0_1/top_level_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_0_1 || ORIG_REF_NAME==top_level_axis_data_fifo_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_dwidth_converter_0_1/top_level_axis_dwidth_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axis_dwidth_converter_0_1 || ORIG_REF_NAME==top_level_axis_dwidth_converter_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_data_fifo_1_1/top_level_axis_data_fifo_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axis_data_fifo_1_1 || ORIG_REF_NAME==top_level_axis_data_fifo_1_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_usp_rf_data_converter_0_1/top_level_usp_rf_data_converter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_1 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_system_ila_0_1/top_level_system_ila_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_system_ila_0_1 || ORIG_REF_NAME==top_level_system_ila_0_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_system_ila_1_1/top_level_system_ila_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_system_ila_1_1 || ORIG_REF_NAME==top_level_system_ila_1_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_rst_top_level_31M_1/top_level_rst_top_level_31M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_rst_top_level_31M_1 || ORIG_REF_NAME==top_level_rst_top_level_31M_1} -quiet] -quiet

# IP: bd/top_level/ip/top_level_clk_wiz_0_0/top_level_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0_0 || ORIG_REF_NAME==top_level_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top_level/ip/top_level_axis_tready_slice_0_0/top_level_axis_tready_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_axis_tready_slice_0_0 || ORIG_REF_NAME==top_level_axis_tready_slice_0_0} -quiet] -quiet

# XDC: bd/top_level/top_level_ooc.xdc
