# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu29dr-ffvf1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.cache/wt [current_project]
set_property parent.project_path C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu1275:part0:1.0 [current_project]
set_property ip_output_repo c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/hdl/top_level_wrapper.v
add_files C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/top_level.bd
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_0_1/top_level_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_0_1/top_level_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_0_1/top_level_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_dlmb_v10_1/top_level_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_dlmb_v10_1/top_level_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_ilmb_v10_1/top_level_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_ilmb_v10_1/top_level_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_dlmb_bram_if_cntlr_1/top_level_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_ilmb_bram_if_cntlr_1/top_level_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_lmb_bram_1/top_level_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_xbar_1/top_level_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_mdm_1_1/top_level_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_mdm_1_1/top_level_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_mdm_1_1/top_level_mdm_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_1_1/top_level_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_1_1/top_level_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_1_1/top_level_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rst_clk_wiz_1_100M_1/top_level_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rst_clk_wiz_1_100M_1/top_level_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rst_clk_wiz_1_100M_1/top_level_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axi_uartlite_0_1/top_level_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axi_uartlite_0_1/top_level_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axi_uartlite_0_1/top_level_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axi_gpio_0_1/top_level_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axi_gpio_0_1/top_level_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axi_gpio_0_1/top_level_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axis_data_fifo_0_1/top_level_axis_data_fifo_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axis_dwidth_converter_0_1/top_level_axis_dwidth_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_axis_data_fifo_1_1/top_level_axis_data_fifo_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_1/synth/top_level_usp_rf_data_converter_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_1/synth/top_level_usp_rf_data_converter_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_1/synth/top_level_usp_rf_data_converter_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_1/top_level_system_ila_0_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_1/bd_0/ip/ip_0/bd_5b7c_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_1/bd_0/bd_5b7c_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_1/top_level_system_ila_1_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_1/bd_0/ip/ip_0/bd_9b2d_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_1_1/bd_0/bd_9b2d_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rst_top_level_31M_1/top_level_rst_top_level_31M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rst_top_level_31M_1/top_level_rst_top_level_31M_1.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_rst_top_level_31M_1/top_level_rst_top_level_31M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/top_level_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_0_1/data/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_1/data/startup.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/constrs_1/new/elab_design.xdc
set_property used_in_implementation false [get_files C:/james/fpga_projects/microblaze_stream_test/microblaze_stream_test.srcs/constrs_1/new/elab_design.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level_wrapper -part xczu29dr-ffvf1760-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_wrapper_utilization_synth.rpt -pb top_level_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
