# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/top_level_rfsoc_adc_data_captu_0_0.xci
# IP: The module: 'top_level_rfsoc_adc_data_captu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_0/rfsoc_adc_data_capture_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_1/rfsoc_adc_data_capture_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_2/rfsoc_adc_data_capture_axis_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_3/rfsoc_adc_data_capture_axis_data_fifo_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_0/rfsoc_adc_data_capture_axis_data_fifo_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_4/rfsoc_adc_data_capture_axis_data_fifo_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_0/rfsoc_adc_data_capture_axis_data_fifo_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_0/rfsoc_adc_data_capture_axis_data_fifo_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_0/rfsoc_adc_data_capture_axis_data_fifo_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_1/rfsoc_adc_data_capture_axis_data_fifo_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_1/rfsoc_adc_data_capture_axis_data_fifo_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_2/rfsoc_adc_data_capture_axis_data_fifo_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_3/rfsoc_adc_data_capture_axis_data_fifo_5_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_4/rfsoc_adc_data_capture_axis_data_fifo_5_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_4} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_adc_data_captu_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/top_level_rfsoc_adc_data_captu_0_0.xci
# IP: The module: 'top_level_rfsoc_adc_data_captu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_0/rfsoc_adc_data_capture_axis_data_fifo_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_1/rfsoc_adc_data_capture_axis_data_fifo_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_2/rfsoc_adc_data_capture_axis_data_fifo_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_3/rfsoc_adc_data_capture_axis_data_fifo_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_0/rfsoc_adc_data_capture_axis_data_fifo_4_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_4/rfsoc_adc_data_capture_axis_data_fifo_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_0/rfsoc_adc_data_capture_axis_data_fifo_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_0/rfsoc_adc_data_capture_axis_data_fifo_2_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_0/rfsoc_adc_data_capture_axis_data_fifo_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_0} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_1/rfsoc_adc_data_capture_axis_data_fifo_4_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_1/rfsoc_adc_data_capture_axis_data_fifo_5_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_2/rfsoc_adc_data_capture_axis_data_fifo_5_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_3/rfsoc_adc_data_capture_axis_data_fifo_5_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_4/rfsoc_adc_data_capture_axis_data_fifo_5_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_4} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_adc_data_captu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
