# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/top_level_rfsoc_adc_data_captu_0_0.xci
# IP: The module: 'top_level_rfsoc_adc_data_captu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_6/rfsoc_adc_data_capture_axis_data_fifo_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_6 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_2/rfsoc_adc_data_capture_axis_data_fifo_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_2/rfsoc_adc_data_capture_axis_data_fifo_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_2/rfsoc_adc_data_capture_axis_data_fifo_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_3/rfsoc_adc_data_capture_axis_data_fifo_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_6/rfsoc_adc_data_capture_axis_data_fifo_5_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_6 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_6_1/rfsoc_adc_data_capture_axis_data_fifo_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_7_1/rfsoc_adc_data_capture_axis_data_fifo_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_8_1/rfsoc_adc_data_capture_axis_data_fifo_8_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_7/rfsoc_adc_data_capture_axis_data_fifo_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_7 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_3/rfsoc_adc_data_capture_axis_data_fifo_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_3/rfsoc_adc_data_capture_axis_data_fifo_2_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_3/rfsoc_adc_data_capture_axis_data_fifo_3_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_4/rfsoc_adc_data_capture_axis_data_fifo_4_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_7/rfsoc_adc_data_capture_axis_data_fifo_5_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_7 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_6_2/rfsoc_adc_data_capture_axis_data_fifo_6_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_7_2/rfsoc_adc_data_capture_axis_data_fifo_7_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_8_2/rfsoc_adc_data_capture_axis_data_fifo_8_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_8/rfsoc_adc_data_capture_axis_data_fifo_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_8 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_4/rfsoc_adc_data_capture_axis_data_fifo_1_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_4/rfsoc_adc_data_capture_axis_data_fifo_2_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_4/rfsoc_adc_data_capture_axis_data_fifo_3_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_5/rfsoc_adc_data_capture_axis_data_fifo_4_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_5 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_8/rfsoc_adc_data_capture_axis_data_fifo_5_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_8 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_6_3/rfsoc_adc_data_capture_axis_data_fifo_6_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_7_3/rfsoc_adc_data_capture_axis_data_fifo_7_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_8_3/rfsoc_adc_data_capture_axis_data_fifo_8_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_register_slice_0_0/rfsoc_adc_data_capture_axis_register_slice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_register_slice_0_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_register_slice_0_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_adc_data_captu_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/top_level_rfsoc_adc_data_captu_0_0.xci
# IP: The module: 'top_level_rfsoc_adc_data_captu_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_6/rfsoc_adc_data_capture_axis_data_fifo_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_6 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_2/rfsoc_adc_data_capture_axis_data_fifo_1_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_2/rfsoc_adc_data_capture_axis_data_fifo_2_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_2/rfsoc_adc_data_capture_axis_data_fifo_3_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_3/rfsoc_adc_data_capture_axis_data_fifo_4_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_6/rfsoc_adc_data_capture_axis_data_fifo_5_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_6 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_6} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_6_1/rfsoc_adc_data_capture_axis_data_fifo_6_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_7_1/rfsoc_adc_data_capture_axis_data_fifo_7_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_8_1/rfsoc_adc_data_capture_axis_data_fifo_8_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_1 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_1} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_7/rfsoc_adc_data_capture_axis_data_fifo_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_7 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_3/rfsoc_adc_data_capture_axis_data_fifo_1_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_3/rfsoc_adc_data_capture_axis_data_fifo_2_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_3/rfsoc_adc_data_capture_axis_data_fifo_3_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_4/rfsoc_adc_data_capture_axis_data_fifo_4_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_7/rfsoc_adc_data_capture_axis_data_fifo_5_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_7 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_7} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_6_2/rfsoc_adc_data_capture_axis_data_fifo_6_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_7_2/rfsoc_adc_data_capture_axis_data_fifo_7_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_8_2/rfsoc_adc_data_capture_axis_data_fifo_8_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_2 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_2} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_0_8/rfsoc_adc_data_capture_axis_data_fifo_0_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_8 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_0_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_1_4/rfsoc_adc_data_capture_axis_data_fifo_1_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_1_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_2_4/rfsoc_adc_data_capture_axis_data_fifo_2_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_2_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_3_4/rfsoc_adc_data_capture_axis_data_fifo_3_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_4 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_3_4} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_4_5/rfsoc_adc_data_capture_axis_data_fifo_4_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_5 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_4_5} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_5_8/rfsoc_adc_data_capture_axis_data_fifo_5_8.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_8 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_5_8} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_6_3/rfsoc_adc_data_capture_axis_data_fifo_6_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_6_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_7_3/rfsoc_adc_data_capture_axis_data_fifo_7_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_7_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_data_fifo_8_3/rfsoc_adc_data_capture_axis_data_fifo_8_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_3 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_data_fifo_8_3} -quiet] -quiet

# IP: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_axis_register_slice_0_0/rfsoc_adc_data_capture_axis_register_slice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_adc_data_capture_axis_register_slice_0_0 || ORIG_REF_NAME==rfsoc_adc_data_capture_axis_register_slice_0_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_adc_data_captu_0_0/src/rfsoc_adc_data_capture_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_adc_data_captu_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
