# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level.bd
# Block Designs: The module: 'top_level' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_gpio_split_0_0/top_level_gpio_split_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_gpio_split_0_0 || ORIG_REF_NAME==top_level_gpio_split_0_0} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/top_level_usp_rf_data_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_RFSoC_Controller_0_1/top_level_RFSoC_Controller_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_RFSoC_Controller_0_1 || ORIG_REF_NAME==top_level_RFSoC_Controller_0_1} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_mcs_0_0 || ORIG_REF_NAME==top_level_microblaze_mcs_0_0} -quiet] -quiet

# Block Designs: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/bd_04f1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1 || ORIG_REF_NAME==bd_04f1} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_microblaze_I_0 || ORIG_REF_NAME==bd_04f1_microblaze_I_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_rst_0_0 || ORIG_REF_NAME==bd_04f1_rst_0_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_04f1_ilmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_ilmb_0 || ORIG_REF_NAME==bd_04f1_ilmb_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_04f1_dlmb_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_dlmb_0 || ORIG_REF_NAME==bd_04f1_dlmb_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_04f1_dlmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_dlmb_cntlr_0 || ORIG_REF_NAME==bd_04f1_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_04f1_ilmb_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_ilmb_cntlr_0 || ORIG_REF_NAME==bd_04f1_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_04f1_lmb_bram_I_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_lmb_bram_I_0 || ORIG_REF_NAME==bd_04f1_lmb_bram_I_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_mdm_0_0 || ORIG_REF_NAME==bd_04f1_mdm_0_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_8/bd_04f1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_xlconcat_0_0 || ORIG_REF_NAME==bd_04f1_xlconcat_0_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_04f1_iomodule_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_iomodule_0_0 || ORIG_REF_NAME==bd_04f1_iomodule_0_0} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0 || ORIG_REF_NAME==top_level_clk_wiz_0} -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_microblaze_mcs_0_0 || ORIG_REF_NAME==top_level_microblaze_mcs_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_microblaze_I_0 || ORIG_REF_NAME==bd_04f1_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0_ooc_debug.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_rst_0_0 || ORIG_REF_NAME==bd_04f1_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_rst_0_0 || ORIG_REF_NAME==bd_04f1_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_04f1_ilmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_ilmb_0 || ORIG_REF_NAME==bd_04f1_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_04f1_dlmb_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_dlmb_0 || ORIG_REF_NAME==bd_04f1_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_04f1_lmb_bram_I_0_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_mdm_0_0 || ORIG_REF_NAME==bd_04f1_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0_ooc_trace.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_04f1_iomodule_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_iomodule_0_0 || ORIG_REF_NAME==bd_04f1_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/bd_04f1_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0 || ORIG_REF_NAME==top_level_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0 || ORIG_REF_NAME==top_level_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0_ooc.xdc

# XDC: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level'. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level.bd
# Block Designs: The module: 'top_level' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_gpio_split_0_0/top_level_gpio_split_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_gpio_split_0_0 || ORIG_REF_NAME==top_level_gpio_split_0_0} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/top_level_usp_rf_data_converter_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_RFSoC_Controller_0_1/top_level_RFSoC_Controller_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_RFSoC_Controller_0_1 || ORIG_REF_NAME==top_level_RFSoC_Controller_0_1} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_microblaze_mcs_0_0 || ORIG_REF_NAME==top_level_microblaze_mcs_0_0} -quiet] -quiet

# Block Designs: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/bd_04f1.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1 || ORIG_REF_NAME==bd_04f1} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_microblaze_I_0 || ORIG_REF_NAME==bd_04f1_microblaze_I_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_rst_0_0 || ORIG_REF_NAME==bd_04f1_rst_0_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_04f1_ilmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_ilmb_0 || ORIG_REF_NAME==bd_04f1_ilmb_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_04f1_dlmb_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_dlmb_0 || ORIG_REF_NAME==bd_04f1_dlmb_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_4/bd_04f1_dlmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_dlmb_cntlr_0 || ORIG_REF_NAME==bd_04f1_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_5/bd_04f1_ilmb_cntlr_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_ilmb_cntlr_0 || ORIG_REF_NAME==bd_04f1_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_04f1_lmb_bram_I_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_lmb_bram_I_0 || ORIG_REF_NAME==bd_04f1_lmb_bram_I_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_mdm_0_0 || ORIG_REF_NAME==bd_04f1_mdm_0_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_8/bd_04f1_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_xlconcat_0_0 || ORIG_REF_NAME==bd_04f1_xlconcat_0_0} -quiet] -quiet

# IP: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_04f1_iomodule_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_04f1_iomodule_0_0 || ORIG_REF_NAME==bd_04f1_iomodule_0_0} -quiet] -quiet

# IP: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0 || ORIG_REF_NAME==top_level_clk_wiz_0} -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_usp_rf_data_converter_0_0 || ORIG_REF_NAME==top_level_usp_rf_data_converter_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_microblaze_mcs_0_0 || ORIG_REF_NAME==top_level_microblaze_mcs_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_microblaze_I_0 || ORIG_REF_NAME==bd_04f1_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0_ooc_debug.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_rst_0_0 || ORIG_REF_NAME==bd_04f1_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_rst_0_0 || ORIG_REF_NAME==bd_04f1_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_04f1_ilmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_ilmb_0 || ORIG_REF_NAME==bd_04f1_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_04f1_dlmb_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_dlmb_0 || ORIG_REF_NAME==bd_04f1_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_04f1_lmb_bram_I_0_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_mdm_0_0 || ORIG_REF_NAME==bd_04f1_mdm_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0_ooc_trace.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_04f1_iomodule_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_04f1_iomodule_0_0 || ORIG_REF_NAME==bd_04f1_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/bd_04f1_ooc.xdc

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0 || ORIG_REF_NAME==top_level_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==top_level_clk_wiz_0 || ORIG_REF_NAME==top_level_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0_ooc.xdc

# XDC: C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level'. Do not add the DONT_TOUCH constraint.
