# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param power.BramSDPPropagationFix 1
set_param chipscope.maxJobs 3
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param synth.incrementalSynthesisCache {C:/Users/Marandi Group B241/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-8868-DESKTOP-6ILET8A/incrSyn}
set_msg_config -id {HDL-1065} -limit 10000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xczu29dr-ffvf1760-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.cache/wt [current_project]
set_property parent.project_path C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu1275:part0:1.0 [current_project]
set_property ip_output_repo c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/new/gpio_split.v
  C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/counter.v
  C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/fire_controller.v
  C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/reg_module.v
  C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/register.v
  C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/RFSoC_Controller.v
}
add_files C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level.bd
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/synth/top_level_usp_rf_data_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/top_level_microblaze_mcs_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/bd_04f1_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_1/bd_04f1_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_2/bd_04f1_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_3/bd_04f1_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_6/bd_04f1_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_7/bd_04f1_mdm_0_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_9/bd_04f1_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/bd_04f1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_0/top_level_clk_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_usp_rf_data_converter_0_0/data/startup.elf]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/ip/top_level_microblaze_mcs_0_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xczu29dr-ffvf1760-2-e -mode out_of_context

rename_ref -prefix_all top_level_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "top_level_synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"

if { [catch {
  file copy -force C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.runs/top_level_synth_1/top_level.dcp C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.ip_user_files/bd/top_level]} {
  catch { 
    file copy -force C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_stub.v C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.ip_user_files/bd/top_level
  }
}

if {[file isdir C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.ip_user_files/bd/top_level]} {
  catch { 
    file copy -force C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.srcs/sources_1/bd/top_level/top_level_stub.vhdl C:/fpga_projects/rfsoc_output_test/rfsoc_output_test.ip_user_files/bd/top_level
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
