# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/top_level_rfsoc_data_pipeline_0_0.xci
# IP: The module: 'top_level_rfsoc_data_pipeline_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_0_10/rfsoc_data_pipeline_axis_data_fifo_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_dwidth_converter_0_10/rfsoc_data_pipeline_axis_dwidth_converter_0_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_waveform_9/rfsoc_data_pipeline_axis_data_fifo_waveform_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_gpio_5/rfsoc_data_pipeline_axis_data_fifo_gpio_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_0_11/rfsoc_data_pipeline_axis_data_fifo_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_11 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_11} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_dwidth_converter_0_11/rfsoc_data_pipeline_axis_dwidth_converter_0_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_11 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_11} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_waveform_10/rfsoc_data_pipeline_axis_data_fifo_waveform_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_gpio_6/rfsoc_data_pipeline_axis_data_fifo_gpio_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_6} -quiet] -quiet

# XDC: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_data_pipeline_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/top_level_rfsoc_data_pipeline_0_0.xci
# IP: The module: 'top_level_rfsoc_data_pipeline_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_0_10/rfsoc_data_pipeline_axis_data_fifo_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_dwidth_converter_0_10/rfsoc_data_pipeline_axis_dwidth_converter_0_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_9} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_waveform_9/rfsoc_data_pipeline_axis_data_fifo_waveform_9.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_9} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_gpio_5/rfsoc_data_pipeline_axis_data_fifo_gpio_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_5} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_0_11/rfsoc_data_pipeline_axis_data_fifo_0_11.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_11 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_0_11} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_dwidth_converter_0_11/rfsoc_data_pipeline_axis_dwidth_converter_0_11.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_11 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_dwidth_converter_0_11} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10/rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_clock_crossing_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_waveform_10/rfsoc_data_pipeline_axis_data_fifo_waveform_10.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_10 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_waveform_10} -quiet] -quiet

# IP: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_axis_data_fifo_gpio_6/rfsoc_data_pipeline_axis_data_fifo_gpio_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_6 || ORIG_REF_NAME==rfsoc_data_pipeline_axis_data_fifo_gpio_6} -quiet] -quiet

# XDC: c:/james/current_repo/RFSoC_Controller/rfsoc_controller/rfsoc_controller.srcs/sources_1/bd/top_level/ip/top_level_rfsoc_data_pipeline_0_0/src/rfsoc_data_pipeline_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_rfsoc_data_pipeline_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
