# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2.xci
# IP: The module: 'top_level_clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2.xci
# IP: The module: 'top_level_clk_wiz_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/fpga_projects/board_microblaze_test/board_microblaze_test.srcs/sources_1/bd/top_level/ip/top_level_clk_wiz_2/top_level_clk_wiz_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_clk_wiz_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
