# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/top_level_system_ila_0_2.xci
# IP: The module: 'top_level_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/bd_5a3c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a3c || ORIG_REF_NAME==bd_5a3c} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/bd_5a3c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a3c_ila_lib_0 || ORIG_REF_NAME==bd_5a3c_ila_lib_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_1/bd_5a3c_g_inst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a3c_g_inst_0 || ORIG_REF_NAME==bd_5a3c_g_inst_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/top_level_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a3c_ila_lib_0 || ORIG_REF_NAME==bd_5a3c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a3c_ila_lib_0 || ORIG_REF_NAME==bd_5a3c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/bd_5a3c_ila_lib_0_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/bd_5a3c_ooc.xdc

# IP: C:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/top_level_system_ila_0_2.xci
# IP: The module: 'top_level_system_ila_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/bd_5a3c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a3c || ORIG_REF_NAME==bd_5a3c} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/bd_5a3c_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a3c_ila_lib_0 || ORIG_REF_NAME==bd_5a3c_ila_lib_0} -quiet] -quiet

# IP: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_1/bd_5a3c_g_inst_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_5a3c_g_inst_0 || ORIG_REF_NAME==bd_5a3c_g_inst_0} -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/top_level_system_ila_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_system_ila_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a3c_ila_lib_0 || ORIG_REF_NAME==bd_5a3c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_5a3c_ila_lib_0 || ORIG_REF_NAME==bd_5a3c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/ip/ip_0/bd_5a3c_ila_lib_0_ooc.xdc

# XDC: c:/james/fpga_projects/microblaze_axi_test/microblaze_axi_test.srcs/sources_1/bd/top_level/ip/top_level_system_ila_0_2/bd_0/bd_5a3c_ooc.xdc
